# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  web_app:
    container_name: web-app
    image: svetlinstoyanovhomiesscr.azurecr.io/web_app
    build:
      # context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    restart: on-failure
    domainname: svetlinstoyanovhomies
  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
        - '1433:1433'
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
        - sqldata:/var/opt/mssql/sqlserver
    container_name: sqlserver
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2GB

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: homiesstorageccsvetlinst